language: objective-c

matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9.2
      script:
        - set -o pipefail
        - xcodebuild -scheme wispr-swift -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.2,name=iPhone X' -configuration Debug test | xcpretty -c
      after_success:
        - bash <(curl -s https://codecov.io/bash)

before_install:
    - carthage update --no-use-binaries
